### ISSUE TITLE
Struggling to deploy on my own endpoint

### ISSUE THREAD

**Issue by tdurand** [kylebarron/naip-cogeo-mosaic#14]
Hi,

 **feel free to close this without answering.. I'm also an Open Source maintainer and I sometimes don't have the time to provide support.**

First, many thanks for all your open work on COGs and map related tools... As an user without much experience in those things it opens lots of possibilities to be able to serve my own tiles from some providers like NAIP 😎️

I read carefully your blog post and the README, but I'm struggling and I don't succeed to deploy my own endpoint for this.

It is the first time I work with Lambda and DynamoDB so I might be doing something wrong.. maybe you have an idea of something I'm doing wrong ? 

Here is what I did:

- cloned the cogeo-mosaic-tiler repo inside this one
- make package
- go back to root, deploy on Lambda with: `sls deploy --region us-west-2 --bucket mybucket --aws-account-id my-aws-account-id`  replacing with my bucket and my aws account id

I get this back from the CLI telling my the lambda deploy went fine

```
Service Information
service: naip-cogeo-mosaic
stage: production
region: us-west-2
stack: naip-cogeo-mosaic-production
resources: 9
api keys:
  None
endpoints:
  ANY - https://8hrrigck3c.execute-api.us-west-2.amazonaws.com/{proxy+}
functions:
  app: naip-cogeo-mosaic-production-app
```

Then I uploaded `naip_2016_2018_mosaic.json` on DynamoDB ([the one from the filled directory](https://github.com/kylebarron/naip-cogeo-mosaic/blob/master/filled/naip_2016_2018_mosaic.json.gz)) using this command

`cogeo-mosaic upload --url 'dynamodb://us-west-2/naip20162018' naip_2016_2018_mosaic.json`

I took example from your live deployment to see if I can request the same tiles.. for example on your deployment this request leads to a tile: https://us-west-2-lambda.kylebarron.dev/naip/14/3105/6429.jpg?url=dynamodb%3A%2F%2Fus-west-2%2F94c61bd217e1211db47cf7f8b95bbc8e5e7d68a26cd9099319cf15f9

So I construct from there the same request adapted to my endpoint, I did this:

https://8hrrigck3c.execute-api.us-west-2.amazonaws.com/14/3105/6429.jpg?url=dynamodb://us-west-2/naip20162018

But the response is: `{"message":"Internal Server Error"}`

Then I went to see the logs of the lambda funcion, and it seems there is a python error: 

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'cogeo_mosaic_tiler.handlers.app': cannot import name 'tile' from 'rio_tiler.io.cogeo' (/var/task/rio_tiler/io/cogeo.pyc)
```

I'm gonna have a look at the https://github.com/developmentseed/cogeo-mosaic-tiler directly as I think the issue comes from there but if this rings any idea let me know.

Thanks again 

Thibault

**Comment by vincentsarago** [comment]
👋 @tdurand, Yeah it all comes done to heavy lifting we did to either rio-tiler and cogeo-mosaic. I hope you can resolve the issue by pining the module to old version 😞

**Comment by kylebarron** [comment]
Yeah..., the main issue is that since I finished everything, all the dependencies have been being upgraded towards 2.0.

For example [here](https://github.com/developmentseed/cogeo-mosaic-tiler/blob/40da225b24869d84d188b60565757411edaebba1/setup.py#L6-L11) in `cogeo-mosaic-tiler`, you can see `rio-tiler>=2.0a9`, but there have been many breaking changes in `rio-tiler` since then, so that doesn't work anymore.

I think you could try pinning
```
    "cogeo-mosaic==3.0a1",
    "lambda-proxy~=5.2",
    "rio-color",
    "rio-tiler==2.0a9",
```
in `cogeo-mosaic-tiler` and it might work.

On the other hand, I'm moving all of my projects to [`titiler`](https://developmentseed.org/titiler/), so I'd recommend that instead. It should "just work" with titiler except that you need to set `AWS_REQUEST_PAYER="requester"` in the [environment](https://github.com/developmentseed/titiler/blob/dafacd57a34aeed2b2d65c7a9cb5579129fd5656/stack/config.py#L17)

**Comment by tdurand** [comment]
Many thanks for the quick answer and please no problem.. You already publish  so many great project with documentation

I'm not really in a hurry to make this work as it is.. I just have time those days to hack around so I will look into https://developmentseed.org/titiler/ as it seems to be the go to for the future, didn't know about it ! If I struggle also I'll just wait you move one project to take it as an example.

I'm very happy to know that you can just have your own endpoint of country /  worldwide raster imagery so easily by directly hooking to the data source instead of being dependent of a third party API provider or needing to host TBs of data yourself.
